# Generated by Django 4.0.6 on 2022-08-22 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Date')),
                ('amount', models.FloatField(verbose_name='Amount')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
                ('status', models.BooleanField(verbose_name='Status')),
                ('error_message', models.TextField(max_length=1000, verbose_name='ErrorMessage')),
                ('receivers_account', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Receiver', to='home.account')),
                ('senders_account', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Sender', to='home.account')),
            ],
            options={
                'verbose_name': 'Transactions',
                'verbose_name_plural': 'Transactions',
            },
        ),
    ]
