# Generated by Django 4.0.6 on 2022-08-22 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_status_id',
            field=models.IntegerField(choices=[('OK', 'OK'), ('BANNED', 'BANNED'), ('JUST NEW', 'JUST NEW')], default=('JUST NEW', 'JUST NEW'), verbose_name='UserStatusId'),
        ),
    ]
