# Generated by Django 4.0.6 on 2022-08-22 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0003_alter_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_status_id',
            field=models.CharField(choices=[('OK', 'OK'), ('BANNED', 'BANNED'), ('JUST NEW', 'JUST NEW')], default=('JUST NEW', 'JUST NEW'), max_length=15, verbose_name='UserStatusId'),
        ),
    ]
