# Generated by Django 4.0.6 on 2022-08-16 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authorization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.IntegerField(verbose_name='AccountNumber')),
                ('balance', models.FloatField(verbose_name='Balance')),
                ('type', models.CharField(max_length=50, verbose_name='Type')),
                ('api_key', models.TextField(max_length=255, verbose_name='APIKey')),
                ('cvv_code', models.IntegerField(verbose_name='CVVCode')),
                ('account_status', models.TextField(max_length=1000, verbose_name='Status')),
                ('owner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authorization.user')),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
            },
        ),
    ]
