# Generated by Django 4.0.6 on 2022-08-22 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_account_account_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_number',
            field=models.IntegerField(default=8730, unique=True, verbose_name='AccountNumber'),
        ),
    ]
