# Generated by Django 4.0.6 on 2022-08-22 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_account_account_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_number',
            field=models.IntegerField(default=1329, unique=True, verbose_name='AccountNumber'),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_status',
            field=models.TextField(default='Just new.', max_length=1000, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.FloatField(default=0, verbose_name='Balance'),
        ),
        migrations.AlterField(
            model_name='account',
            name='cvv_code',
            field=models.IntegerField(default=229, unique=True, verbose_name='CVVCode'),
        ),
        migrations.AlterField(
            model_name='account',
            name='type',
            field=models.CharField(choices=[('Deposit', 'Deposit'), ('Debit', 'Debit')], max_length=50, verbose_name='Type'),
        ),
    ]
