# Generated by Django 4.1 on 2022-09-12 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_account_account_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_number',
            field=models.IntegerField(default=2494, unique=True, verbose_name='AccountNumber'),
        ),
        migrations.AlterField(
            model_name='account',
            name='cvv_code',
            field=models.IntegerField(default=728, unique=True, verbose_name='CVVCode'),
        ),
    ]
