# Generated by Django 4.1 on 2022-09-12 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_account_account_number_alter_account_cvv_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_number',
            field=models.IntegerField(default=7575, unique=True, verbose_name='AccountNumber'),
        ),
        migrations.AlterField(
            model_name='account',
            name='cvv_code',
            field=models.IntegerField(default=665, unique=True, verbose_name='CVVCode'),
        ),
    ]
