# Generated by Django 4.0.6 on 2022-09-12 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_account_account_number_alter_account_cvv_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_number',
            field=models.IntegerField(unique=True, verbose_name='AccountNumber'),
        ),
        migrations.AlterField(
            model_name='account',
            name='cvv_code',
            field=models.IntegerField(unique=True, verbose_name='CVVCode'),
        ),
    ]
